//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZodiacSign.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class znak_dbEntities : DbContext
    {
        private static znak_dbEntities _context;
        public znak_dbEntities()
            : base("name=znak_dbEntities")
        {
        }
        public static znak_dbEntities GetContext()
        {
            if (_context == null)
                _context = new znak_dbEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<zodiacSign> zodiacSign { get; set; }
    }
}
