//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZodiacSign.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class zodiacSign
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string sign { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
    }
}
